---
- hosts: mywebservers
  become: yes 
  tasks: 
  - name: in this task i want to install java on ubuntu
    apt:
      name: "{{myjavaonubuntu}}" 
      state: present 
    when: ansible_os_family== "Debian"